export const OBJECTIVES_HAND = "OBJECTIVES_HAND";
export const POWERS_HAND = "POWERS_HAND";
export const OBJECTIVES_SCORED = "OBJECTIVES_SCORED";
export const OBJECTIVES_DISCARDED = "OBJECTIVES_DISCARDED";
export const POWERS_DISCARDED = "POWERS_DISCARDED";
export const MY_CARDS_GROUP = "MY_CARDS_GROUP";
export const ENEMY_CARDS_GROUP = "ENEMY_CARDS_GROUP";
