export const INITIATIVE_ROLL = "INITIATIVE_ROLL";
export const BOARDS_PLACEMENT_ORDER = "BOARDS_PLACEMENT_ORDER";
export const PICK_FIRST_BOARD = "PICK_FIRST_BOARD";
export const PICK_SECOND_BOARD = "PICK_SECOND_BOARD";
